### PR TITLE
Updated build scripts

### PR DESCRIPTION
**Pull request by neutrinog**
Related to https://github.com/unfoldingWord-dev/translationCore/issues/4960

This improves the build scripts so that...

* the module can be installed directly from github if needed
* the module compiles to pure es5 without any babel runtime requirements.

---
This change is [Reviewable](https://reviewable.io/reviews/translationcoreapps/tc-source-content-updater/34)

### CODE REVIEW

**Comment by mannycolon** [comment]
After installing the branch of the npm package in `tC`I got the following errors.

I used the following npm command: `npm i translationCoreApps/tc-source-content-updater#enhancemt/joel/build_scripts`
```
Uncaught Error: Cannot find module 'tc-source-content-updater'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/Users/mannycolon/Projects/translationCore/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/mannycolon/Projects/translationCore/src/js/actions/SourceContentUpdatesActions.js:4:1)
    at Object.<anonymous> (/Users/mannycolon/Projects/translationCore/src/js/actions/SourceContentUpdatesActions.js:134:3)
    at Module._compile (module.js:571:32)
    at loader (/Users/mannycolon/Projects/translationCore/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/mannycolon/Projects/translationCore/node_modules/babel-register/lib/node.js:154:7)
```

**Comment by neutrinog** [comment]
@mannycolon you misspelled the branch name.

**Comment by mannycolon** [comment]
@neutrinog That's weird I copied it from your branch name up in the top of this page.
Let me try that again.

**Comment by mannycolon** [comment]
@neutrinog I ran it again and still getting the same error
```
npm i translationCoreApps/tc-source-content-updater#enhancement/joel/build_scripts
```

**Comment by neutrinog** [comment]
@mannycolon I copy and pasted that exact command in your previous comment and successfully installed it.

image

Not sure what to tell you.

**Comment by mannycolon** [comment]
@neutrinog Did you opened tC after installing it ?

**Comment by mannycolon** [comment]
@neutrinog Did you opened tC after installing it?

**Comment by neutrinog** [comment]
yes I can start tc and download content.

**Comment by neutrinog** [comment]
@mannycolon can you install this? `npm i translationCoreApps/tc-source-content-updater#master`

This will just install the master branch (e.g. the current working version)

**Comment by RoyalSix** [comment]
Same error for me @neutrinog

**Comment by PhotoNomad0** [comment]
@neutrinog @mannycolon @RoyalSix - I was able to get it to install (copied and pasted joels line) in both develop and 1.0.2 on Mac (Windows is a whole different story though!)

**Comment by neutrinog** [comment]
I just tested this on windows and it works fine.

However, @PhotoNomad0  @RoyalSix @mannycolon installing via git is by no means the primary feature in this PR. It's handy but you can still clone and do an npm link.

Can someone confirm the actual changes to transpilation are working correctly?

**Comment by PhotoNomad0** [comment]
@neutrinog @mannycolon @RoyalSix - I was able to get to work.  I vote pass it.

**Comment by mannycolon** [comment]
Local Testing: `LGTM`

**Pull request merged**
